name: Mirage

on:
  workflow_dispatch:

jobs:
  build:
    name: Build caldav
    runs-on: ubuntu-latest
    steps:
    - name: Clone caldav
      uses: actions/checkout@v4
      with:
        repository: roburio/caldav
        ref: 51f0d150542348dc259b7c9f7bc70ee592243f7f
    - name: Use OCaml ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 4.14.x
        opam-depext: false
    - run: opam repo set-url default git+https://github.com/ocaml/opam-repository#dc24cade5f037058a4d86fcdd008159923152db5
    - run: sed -i s/1.3/2.7/ dune-project
    - run: opam pin add -n dune.dev git+https://github.com/ocaml/dune#$GITHUB_SHA
    - run: sudo apt install libseccomp-dev
    - run: opam install mirage opam-monorepo.0.3.6
    - run: cd mirage; opam exec -- mirage configure -f config.ml -t hvt
    - run: cd mirage; opam exec -- make depend lock pull build
